### ISSUE TITLE
Mobile browser tries to download the page

### ISSUE THREAD

**Issue by filipewl** [PaulKinlan/webgde-deck#75]
Hello. I heard about this project while reading Paul's blog and when I visit https://webgdedeck.com on my Android phone, the browser (Chrome, Opera, Firefox Focus) triggers a download instead of opening the page. I haven't checked if this error happens in the desktop yet.

**Comment by PaulKinlan** [comment]
Yeah, I think it's fixed now. I saw it too...

**Comment by filipewl** [comment]
It's fixed indeed. Thanks!
